name: Publish Plugin

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to publish'
        required: true
      ref:
        description: 'Branch to publish from'
        required: false
        default: 'splendo/publish'

jobs:
  gradle:
    runs-on: macos-15
    permissions:
      contents: read
      packages: write
    env:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Publish to Maven Central
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: 'publishToMavenCentral'
          build-root-directory: SKIE
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
